import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Quicksand, Mystery_Quest, Press_Start_2P } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['latin'], variable: '--font-quicksand' })
const mystery = Mystery_Quest({ subsets: ['latin'], weight: '400', variable: '--font-mystery' })
const pixel = Press_Start_2P({ subsets: ['latin'], weight: '400', variable: '--font-pixel' })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${quicksand.variable} ${mystery.variable} ${pixel.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
